version: '3'

services:
  mongodb:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=git
      - MONGO_INITDB_ROOT_PASSWORD=260396
    ports:
      - "27017:27017"

  example-service:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - "mongodb"
    environment:
      DEMO_MONGO_CONN_STR: mongodb://quanthu.life/UserDB
